[package]
name = "tvisor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
name = "tvisor_util"
crate-type = ["rlib"]
path = "tvisor_util/lib.rs"

[[bin]]
name = "tvisor"
path = "src/main.rs"

[dependencies]
dtoolkit = { path = "third_party/dtoolkit", default-features = false }
linked_list_allocator = { version = "=0.10.6", default-features = false }
spin = { version = "=0.10.1", default-features = false, features = ["mutex", "once", "spin_mutex"] }
